# Generated by Django 5.1.4 on 2024-12-12 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapati',
            old_name='chapati_description',
            new_name='category_description',
        ),
        migrations.RenameField(
            model_name='chapati',
            old_name='chapati_choice',
            new_name='dish_name',
        ),
        migrations.RenameField(
            model_name='chapati',
            old_name='chapati_price',
            new_name='dish_price',
        ),
    ]
