# Generated by Django 5.1.4 on 2024-12-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_chapati_description_chapati_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapati',
            options={'verbose_name': 'Chapati', 'verbose_name_plural': 'Chapatis'},
        ),
    ]
